### ISSUE TITLE
Generic 'Server Error' after some users upload files

### ISSUE THREAD

**Issue by TiCampbell** [Get-Your/Get-Your#336]
**Describe the bug**
Multiple users report seeing the generic 'Server Error' screen after uploading their files, which I've traced to this exception message:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view app.views.application.files didn't return an HttpResponse object. It returned None instead.
```

which is immediately preceded by:

```
Traceback (most recent call last):
  File "/code/app/views/application.py", line 1476, in files
    target_page = finalize_application(
  File "/code/app/backend.py", line 999, in finalize_application
    f"User auto-applied for '{program.program_name}' IQ program",
AttributeError: 'IQProgram' object has no attribute 'program_name'
```

**To Reproduce**
This isn't readily reproducible; it seems to stem from the [known, but not documented] issue of multiple records being created for auto-apply program(s).

**Expected behavior**
I would expect this doesn't happen.

If the issue is that the form is submitting multiple times (as I suspect), then `backend.finalize_application` is being called multiple times with `users_iq_programs` pulling new data from the database each time. When the auto-apply program(s) exist in the database, the program in `users_iq_programs` is represented by an `IQProgram` object (rather than an `IQProgramRD` object when the users hasn't applied to that program); `IQProgram` objects don't have a `program_name` attribute, so the logging command that's expecting an `IQProgramRD` object results in an error.

**Desktop (please complete the following information):**
Multiple

**Smartphone (please complete the following information):**
Multiple

**Comment by TiCampbell** [comment]
If this is what it appears, it will be resolved in the upcoming release (with the admin panel).

**Comment by TiCampbell** [comment]
This hasn't come up since the release specified in my previous comment; closing as successfully resolved.
